export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_RECEIVED = 'FETCH_PRODUCTS_RECEIVED';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_RECEIVED = 'FETCH_CATEGORIES_RECEIVED';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';
export const FETCH_PRODUCT_RECEIVED = 'FETCH_PRODUCT_RECEIVED';

export const FETCH_ATTRIBUTES = 'FETCH_ATTRIBUTES';
export const FETCH_ATTRIBUTES_FAILED = 'FETCH_ATTRIBUTES_FAILED';
export const FETCH_ATTRIBUTES_RECEIVED = 'FETCH_ATTRIBUTES_RECEIVED';

export const FETCH_CART_ID = 'FETCH_CART_ID';
export const FETCH_CART_ID_RECEIVED = 'FETCH_CART_ID_RECEIVED';
export const FETCH_CART_ID_FAILED = 'FETCH_CART_ID_FAILED';

export const SAVE_CART = 'SAVE_CART';
export const SAVE_CART_RECIEVED = 'SAVE_CART_RECIEVED';
export const SAVE_CART_FAILED = 'SAVE_CART_FAILED';

export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_RECIEVED = 'UPDATE_CART_RECIEVED';
export const UPDATE_CART_FAILED = 'UPDATE_CART_FAILED';

export const FETCH_TOTAL_AMOUNT = 'FETCH_TOTAL_AMOUNT';
export const TOTAL_AMOUNT_RECIEVED = 'TOTAL_AMOUNT_RECIEVED';
export const TOTAL_AMOUNT_FAILED = 'TOTAL_AMOUNT_FAILED';

export const FETCH_CART_COUNT = 'FETCH_CART_COUNT';
export const FETCH_CART_COUNT_RECIEVED = 'FETCH_CART_COUNT_RECIEVED';
export const FECTH_CART_COUNT_FAILED = 'FECTH_CART_COUNT_FAILED';

export const RESET = 'RESET';
// export const LOGOUT = 'LOGOUT';
