export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_RECEIVED = 'FETCH_PRODUCTS_RECEIVED';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_RECEIVED = 'FETCH_CATEGORIES_RECEIVED';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';
export const FETCH_PRODUCT_RECEIVED = 'FETCH_PRODUCT_RECEIVED';

// export const FETCH_VIDEOS = 'FETCH_VIDEOS';
// export const VIDEOS_RECEIVED = 'FETCH_VIDEOS_RECEIVED';
// export const VIDEOS_REQUEST_FAILED = 'VIDEOS_REQUEST_FAILED';
// export const SET_LOADING_TO_FALSE = 'SET_LOADING_TO_FALSE';
// export const SEGMENT_MAX_TIME_ERROR = 'SEGMENT_MAX_TIME_ERROR';
// export const SAVE_SEGMENT = 'SAVE_SEGMENT';
// export const SAVE_RECEIVED = 'SAVE_RECEIVED';
// export const SAVE_FAILED = 'SAVE_FAILED';
// export const EDIT_SEGMENT = 'EDIT_SEGMENT';
// export const EDIT_RECEIVED = 'EDIT_RECEIVED';
// export const EDIT_FAILED = 'EDIT_FAILED';
// export const FETCH_SEGMENT = 'FETCH_SEGMENT';
// export const FETCH_SEGMENT_RECEIVED = 'FETCH_SEGMENT_RECEIVED';
// export const FETCH_SEGMENT_FAILED = 'FETCH_SEGMENT_FAILED';
// export const FETCH_SEGMENT_STATUS = 'FETCH_SEGMENT_STATUS';
// export const FETCH_SEGMENT_STATUS_RECEIVED = 'FETCH_SEGMENT_STATUS_RECEIVED';
// export const FETCH_SEGMENT_STATUS_FAILED = 'FETCH_SEGMENT_STATUS_FAILED';
// export const FETCH_ADS = 'FETCH_ADS';
// export const FETCH_ADS_RECEIVED = 'FETCH_ADS_RECEIVED';
// export const FETCH_ADS_FAILED = 'FETCH_ADS_FAILED';
// export const FETCH_BUMPERS = 'FETCH_BUMPERS';
// export const FETCH_BUMPERS_RECEIVED = 'FETCH_BUMPERS_RECEIVED';
// export const FETCH_BUMPERS_FAILED = 'FETCH_BUMPERS_FAILED';
// export const FETCH_PRODUCERS = 'FETCH_PRODUCERS'
// export const FETCH_PRODUCERS_RECEIVED = 'FETCH_PRODUCERS_RECEIVED';
// export const FETCH_PRODUCERS_FAILED = 'FETCH_PRODUCERS_FAILED';
// export const BULK_DELETE_SEGMENTS = 'BULK_DELETE_SEGMENTS';
// export const BULK_DELETE_SEGMENTS_RECEIVED = 'BULK_DELETE_SEGMENTS_RECEIVED';
// export const BULK_DELETE_SEGMENTS_FAILED = 'BULK_DELETE_SEGMENTS_FAILED';

// export const DELETE_SEGMENT = 'DELETE_SEGMENT';
// export const DELETE_SEGMENT_RECEIVED = 'DELETE_SEGMENT_RECEIVED';
// export const DELETE_FAILED = 'DELETE_FAILED';

// export const SEGMENT_VALIDATION_ERROR = 'SEGMENT_VALIDATION_ERROR';

export const RESET = 'RESET';
// export const LOGOUT = 'LOGOUT';

// export const SAVE_LIVESTREAM = 'SAVE_LIVESTREAM';
// export const SAVE_LIVESTREAM_RECEIVED = 'SAVE_LIVESTREAM_RECEIVED';
// export const FETCH_LIVESTREAMS = 'FETCH_LIVESTREAMS';
// export const LIVESTREAMS_RECEIVED = 'FETCH_LIVESTREAMS_RECEIVED';
// export const LIVESTREAMS_REQUEST_FAILED = 'LIVESTREAMS_REQUEST_FAILED';
// export const FETCH_LIVESTREAM = 'FETCH_LIVESTREAM';
// export const FETCH_LIVESTREAM_RECEIVED = 'FETCH_LIVESTREAM_RECEIVED';
// export const FETCH_LIVESTREAM_FAILED = 'FETCH_LIVESTREAM_FAILED';
// export const UPDATE_LIVESTREAM = 'UPDATE_LIVESTREAM';
// export const UPDATE_LIVESTREAM_RECEIVED = 'UPDATE_LIVESTREAM_RECEIVED';
// export const UPDATE_LIVESTREAM_FAILED = 'UPDATE_LIVESTREAM_FAILED';
// export const FETCH_LIVESTREAM_STATUS = 'FETCH_LIVESTREAM_STATUS';
// export const FETCH_LIVESTREAM_STATUS_RECEIVED = 'FETCH_LIVESTREAM_STATUS_RECEIVED';
// export const FETCH_LIVESTREAM_STATUS_FAILED = 'FETCH_LIVESTREAM_STATUS_FAILED';
// export const BULK_DELETE_LIVESTREAMS = 'BULK_DELETE_LIVESTREAMS';
// export const BULK_DELETE_LIVESTREAMS_RECEIVED = 'BULK_DELETE_LIVESTREAMS_RECEIVED';
// export const BULK_DELETE_LIVESTREAMS_FAILED = 'BULK_DELETE_LIVESTREAMS_FAILED';


// export const DELETE_LIVESTREAM = 'DELETE_LIVESTREAM';
// export const DELETE_LIVESTREAM_RECEIVED = 'DELETE_LIVESTREAM_RECEIVED';

// export const FETCH_SCHEDULES = 'FETCH_SCHEDULES';
// export const SCHEDULES_RECEIVED = 'FETCH_SCHEDULES_RECEIVED';
// export const SCHEDULES_REQUEST_FAILED = 'SCHEDULES_REQUEST_FAILED';
// export const BULK_DELETE_SCHEDULES_RECEIVED = 'BULK_DELETE_SCHEDULES_RECEIVED';
// export const BULK_DELETE_SCHEDULES_FAILED = 'BULK_DELETE_SCHEDULES_FAILED';
// export const BULK_DELETE_SCHEDULES = 'BULK_DELETE_SCHEDULES';

// export const FETCH_TOKEN = 'FETCH_TOKEN';
// export const TOKEN = 'TOKEN';
// export const TOKEN_FAILED = 'TOKEN_FAILED';
// export const SET_PARTNER_ID = 'SET_PARTNER_ID';
// export const FETCH_VIDEO_ACCESS_RIGHTS = 'FETCH_VIDEO_ACCESS_RIGHTS';
// export const VIDEO_ACCESS_SETTINGS_RECEIVED = "VIDEO_ACCESS_SETTINGS_RECEIVED";
// export const VIDEO_ACCESS_SETTINGS_FAILED = "VIDEO_ACCESS_SETTINGS_FAILED";

// export const SAVE_SCHEDULE = 'SAVE_SCHEDULE';
// export const SAVE_SCHEDULE_RECEIVED = 'SAVE_SCHEDULE_RECEIVED';
// export const SAVE_SCHEDULE_FAILED = 'SAVE_SCHEDULE_FAILED';
// export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
// export const UPDATE_SCHEDULE_RECEIVED = 'UPDATE_SCHEDULE_RECEIVED';
// export const UPDATE_SCHEDULE_FAILED = 'UPDATE_SCHEDULE_FAILED';
// export const SCHEDULE_VALIDATION_ERROR = 'SCHEDULE_VALIDATION_ERROR';
// export const FETCH_SCHEDULE = 'FETCH_SCHEDULE';
// export const FETCH_SCHEDULE_RECEIVED = 'FETCH_SCHEDULE_RECEIVED';
// export const FETCH_SCHEDULE_FAILED = 'FETCH_SCHEDULE_FAILED';
// export const SCHEDULE_LIMIT_REACHED = 'SCHEDULE_LIMIT_REACHED';
// export const UPDATE_SCHEDULE_CONFLICT = 'UPDATE_SCHEDULE_CONFLICT';

// export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
// export const DELETE_SCHEDULE_RECEIVED = 'DELETE_SCHEDULE_RECEIVED';
// export const DELETE_SCHEDULE_FAILED = 'DELETE_SCHEDULE_FAILED';
// export const DELETE_RECURRING = 'DELETE_RECURRING';
// export const DELETE_RECURRING_RECEIVED = 'DELETE_RECURRING_RECEIVED';
// export const DELETE_RECURRING_FAILED = 'DELETE_RECURRING_FAILED';


// export const CLONE_SCHEDULE = 'CLONE_SCHEDULE';
// export const CLONE_SCHEDULE_RECEIVED = 'CLONE_SCHEDULE_RECEIVED';
// export const CLONE_SCHEDULE_FAILED = 'CLONE_SCHEDULE_FAILED';

// export const FETCH_SETTINGS = 'FETCH_SETTINGS';
// export const FETCH_SETTINGS_RECEIVED = 'FETCH_SETTINGS_RECEIVED';
// export const FETCH_SETTINGS_FAILED = 'FETCH_SETTINGS_FAILED';

// //notification related
// export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
// export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';

// // schedule warning
// export const OVERLAPPING_SEGMENTS = 'OVERLAPPING_SEGMENTS';
// export const OVERLAPPING_LIVESTREAMS = 'OVERLAPPING_LIVESTREAMS';
// export const OVERLAPPING_START_DATETIME = 'OVERLAPPING_START_DATETIME';
// export const OVERLAPPING_SEGMENT = 'OVERLAPPING_SEGMENT';
// export const INVALID_TIMESLOTS = 'INVALID_TIMESLOTS';
// export const UNLOCK_PAST_EVENT = 'UNLOCK_PAST_EVENT';
// export const END_DATETIME_BEFORE_START = 'END_DATETIME_BEFORE_START';
// export const INVALID_TIMESLOTS_FOR_UPDATE = 'INVALID_TIMESLOTS_FOR_UPDATE';
