export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_RECEIVED = 'FETCH_PRODUCTS_RECEIVED';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_RECEIVED = 'FETCH_CATEGORIES_RECEIVED';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS';
export const FETCH_DEPARTMENTS_RECEIVED = 'FETCH_DEPARTMENTS_RECEIVED';
export const FETCH_DEPARTMENTS_FAILED = 'FETCH_DEPARTMENTS_FAILED';

export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';
export const FETCH_PRODUCT_RECEIVED = 'FETCH_PRODUCT_RECEIVED';

export const FETCH_ATTRIBUTES = 'FETCH_ATTRIBUTES';
export const FETCH_ATTRIBUTES_FAILED = 'FETCH_ATTRIBUTES_FAILED';
export const FETCH_ATTRIBUTES_RECEIVED = 'FETCH_ATTRIBUTES_RECEIVED';

export const FETCH_CART_ID = 'FETCH_CART_ID';
export const FETCH_CART_ID_RECEIVED = 'FETCH_CART_ID_RECEIVED';
export const FETCH_CART_ID_FAILED = 'FETCH_CART_ID_FAILED';

export const SAVE_CART = 'SAVE_CART';
export const SAVE_CART_RECIEVED = 'SAVE_CART_RECIEVED';
export const SAVE_CART_FAILED = 'SAVE_CART_FAILED';

export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_RECIEVED = 'UPDATE_CART_RECIEVED';
export const UPDATE_CART_FAILED = 'UPDATE_CART_FAILED';

export const FETCH_TOTAL_AMOUNT = 'FETCH_TOTAL_AMOUNT';
export const TOTAL_AMOUNT_RECIEVED = 'TOTAL_AMOUNT_RECIEVED';
export const TOTAL_AMOUNT_FAILED = 'TOTAL_AMOUNT_FAILED';

export const FETCH_CART_COUNT = 'FETCH_CART_COUNT';
export const FETCH_CART_COUNT_RECIEVED = 'FETCH_CART_COUNT_RECIEVED';
export const FECTH_CART_COUNT_FAILED = 'FECTH_CART_COUNT_FAILED';

export const FETCH_ALL_CARTS = 'FETCH_ALL_CARTS';
export const FETCH_ALL_CARTS_RECEIVED = 'FETCH_ALL_CARTS_RECEIVED';
export const FETCH_ALL_CARTS_FAILED = 'FETCH_ALL_CARTS_FAILED'

export const EMPTY_CARTS = 'EMPTY_CARTS';
export const EMPTY_CARTS_RECEIVED = 'EMPTY_CARTS_RECEIVED';
export const EMPTY_CARTS_FAILED = 'EMPTY_CARTS_FAILED';

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_PRODUCT_RECEIVED = 'REMOVE_PRODUCT_RECEIVED';
export const REMOVE_PRODUCT_FAILED = 'REMOVE_PRODUCT_FAILED';


export const RESET = 'RESET';
export const LOGOUT = 'LOGOUT';

export const FETCH_TOKEN = 'FETCH_TOKEN';
export const TOKEN = 'TOKEN';
export const TOKEN_FAILED = 'TOKEN_FAILED';


export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_CUSTOMER = 'REGISTER_CUSTOMER';

export const SET_CUSTOMER_ID = 'SET_CUSTOMER_ID';

export const FETCH_CUSTOMER_DETAILS = 'FETCH_CUSTOMER_DETAILS';
export const FETCH_CUSTOMER_DETAILS_RECEIVED = 'FETCH_CUSTOMER_DETAILS_RECEIVED';
export const FETCH_CUSTOMER_DETAILS_FAILED = 'FETCH_CUSTOMER_DETAILS_FAILED';


export const FETCH_SHIPPING_REGION = 'FETCH_SHIPPING_REGION';
export const FETCH_SHIPPING_REGION_RECEIVED = 'FETCH_SHIPPING_REGION_RECEIVED';
export const FETCH_SHIPPING_REGION_FAILED = 'FETCH_SHIPPING_REGION_FAILED';

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_ADDRESS_RECEIVED = 'UPDATE_ADDRESS_RECEIVED';
export const UPDATE_ADDRESS_FAILED = 'UPDATE_ADDRESS_FAILED';

export const UPDATE_REGION_ADDRESS = 'UPDATE_REGION_ADDRESS';
export const UPDATE_REGION_ADDRESS_RECEIVED = 'UPDATE_REGION_ADDRESS_RECEIVED';
export const UPDATE_REGION_ADDRESS_FAILED = 'UPDATE_REGION_ADDRESS_FAILED';

export const FETCH_TAX = 'FETCH_TAX';
export const FETCH_TAX_RECEIVED = 'FETCH_TAX_RECEIVED';
export const FETCH_TAX_FAILED = 'FETCH_TAX_FAILED';

export const FETCH_SHIPPING_REGION_PRICE = 'FETCH_SHIPPING_REGION_PRICE';
export const FETCH_SHIPPING_REGION_PRICE_RECEIVED = 'FETCH_SHIPPING_REGION_PRICE_RECEIVED';
export const FETCH_SHIPPING_REGION_PRICE_FAILED = 'FETCH_SHIPPING_REGION_PRICE_FAILED';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_RECEIVED = 'CREATE_ORDER_RECEIVED';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';

export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const MAKE_PAYMENT_RECEIVED = "MAKE_PAYMENT_RECEIVED";
export const MAKE_PAYMENT_FAILED = "MAKE_PAYMENT_FAILED";


export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
export const FETCH_ORDERS_RECEIVED = "FETCH_ORDERS_RECEIVED";

export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED";
export const FETCH_ORDER_RECEIVED = "FETCH_ORDER_RECEIVED";

export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const SEARCH_PRODUCT_RECEIVED = "SEARCH_PRODUCT_RECEIVED";
export const SEARCH_PRODUCT_FAILED = "SEARCH_PRODUCT_FAILED";

export const FETCH_PRODUCTS_CATEGORY_RECEIVED = "FETCH_PRODUCTS_CATEGORY_RECEIVED";
export const FETCH_PRODUCTS_CATEGORY_FAILED = "FETCH_PRODUCTS_CATEGORY_FAILED";
export const FETCH_PRODUCTS_CATEGORY = "FETCH_PRODUCTS_CATEGORY";

export const FETCH_PRODUCTS_DEPARTMENT_RECEIVED = "FETCH_PRODUCTS_DEPARTMENT_RECEIVED";
export const FETCH_PRODUCTS_DEPARTMENT_FAILED = "FETCH_PRODUCTS_DEPARTMENT_FAILED";
export const FETCH_PRODUCTS_DEPARTMENT = "FETCH_PRODUCTS_DEPARTMENT";

export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const UPDATE_QUANTITY_RECEIVED = 'UPDATE_QUANTITY_RECEIVED';
export const UPDATE_QUANTITY_FAILED = 'UPDATE_QUANTITY_FAILED';

export const FETCH_COLOR_ATTRIBUTES = 'FETCH_COLOR_ATTRIBUTES';
export const ATTRIBUTES_COLOR_RECEIVED = 'ATTRIBUTES_COLOR_RECEIVED';
export const ATTRIBUTES_COLOR_FAILED = 'ATTRIBUTES_COLOR_FAILED';

export const FETCH_SIZE_ATTRIBUTES = 'FETCH_SIZE_ATTRIBUTES';
export const ATTRIBUTES_SIZE_RECEIVED = 'ATTRIBUTES_SIZE_RECEIVED';
export const ATTRIBUTES_SIZE_FAILED = 'ATTRIBUTES_SIZE_FAILED';

export const UPDATE_CC = 'UPDATE_CC';



//notification related
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';

